### ISSUE TITLE
Can't use the pack picker

### ISSUE THREAD

**Issue by StormDragon-64** [7eventy7/Self-Serve#18]
### Description of bug

When I try to use the link to the pack picker, it gives me the error shown in the screenshot below. I ran network diagnostics, reloaded multiple times, and even tried using a different browser.

### Additional information
Add any other info about the problem here. Include screenshots, if possible.
![image](https://user-images.githubusercontent.com/80718549/129285888-774194af-3056-4de1-ba64-4a9eb6fdade4.png)

### Your selectedModules.txt
Please upload your selectedModules.txt here, if possible. You can find it within your pack download.
If it is easier, or it would be more helpful, you can also upload the whole download from the site.

**Comment by Unknown-64** [comment]
Oh, and I don't know what I did, but one time it did this:
![image](https://user-images.githubusercontent.com/80718549/129286321-0b500f61-7bc2-48ca-b3d1-68a68236babc.png)

**Comment by Unknown-64** [comment]
Figured out how I was able to show stuff about replit.com.
Turns out I tried adding a www. at the beginning of selfserve.tk, and that is what happened when I did that.
