### ISSUE TITLE
malformed dropbox access token

### ISSUE THREAD

**Issue by 7eventy7** [7eventy7/Self-Serve#5]
Trying to download any packs on the site results in a frozen page
https://self-serve.7eventy7.repl.co/

**Comment by Beatso** [comment]
I'll take a look at this later. @7eventy7, when you press download, do you get any errors in the replit console?

**Comment by 7eventy7** [comment]
yes

`Server running
packID = 99L5K
[ 'darkerDarkOak' ]
pack generated at /tmp/99L5K.zip
DropboxResponseError: Response failed with a 400 code
    at /home/runner/Self-Serve/LittleImprovementsCustom/src/node_modules/dropbox/cjs/src/response.js:34:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      server: [Array],
      date: [Array],
      'content-type': [Array],
      'content-security-policy': [Array],
      'x-dropbox-request-id': [Array],
      'x-robots-tag': [Array],
      'strict-transport-security': [Array],
      'content-encoding': [Array],
      vary: [Array],
      connection: [Array],
      'transfer-encoding': [Array]
    }
  },
  error: 'Error in call to API function "files/upload": The given OAuth 2 access token is malformed.'
}
packID = WI06Q
[ 'darkerDarkOak', 'whiterBirch' ]
pack generated at /tmp/WI06Q.zip
 cd LittleImprovementsCustom && git pull && cd src && npm start
Already up-to-date.

> littleimprovements-custom@1.0.0 start /home/runner/Self-Serve/LittleImprovementsCustom/src
> node app

Server running
packID = 1WJ8Z
[ 'darkerDarkOak', 'whiterBirch' ]
pack generated at /tmp/1WJ8Z.zip
DropboxResponseError: Response failed with a 400 code
    at /home/runner/Self-Serve/LittleImprovementsCustom/src/node_modules/dropbox/cjs/src/response.js:34:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      server: [Array],
      date: [Array],
      'content-type': [Array],
      'content-security-policy': [Array],
      'x-dropbox-request-id': [Array],
      'x-robots-tag': [Array],
      'strict-transport-security': [Array],
      'content-encoding': [Array],
      vary: [Array],
      connection: [Array],
      'transfer-encoding': [Array]
    }
  },
  error: 'Error in call to API function "files/upload": The given OAuth 2 access token is malformed.'
}`

**Comment by Beatso** [comment]
ok, we can debug on discord later

**Comment by Beatso** [comment]
.env file was in the wrong folder on repl.it. fixed together on discord
